stages:
- compile
- build
- registry
- deploy:review
- deploy:uat
- deploy:prod

variables:
  _img_repo: $CI_REGISTRY_IMAGE
  _img_name: emiswap-info-$CI_COMMIT_REF_SLUG
  _app_name: emiswap-info
  _img_short_name: emiswap-info
  _env_name: emiswap-info-$CI_COMMIT_REF_SLUG
  _node_image: node:12.19.0

include:
- project: emirex-exchange/devops/pipelines
  file: emiswap.yaml
  ref: dev

compile:
  stage: compile
  image: $_node_image
  artifacts:
    name: $_img_short_name-$CI_COMMIT_REF_SLUG
    paths:
    - build/
  script:
  - unset CI
  - npm install
  - npm run build
  tags:
  - hetzner
  - docker

build:production:
  extends: .build:react
  stage: build
  needs:
  - compile
  only:
  - production
  - tags
  script:
  - find ./build -iname \*.map -exec rm {} \;
  - docker build -t $_img_repo/$_img_name:$_img_tag . --no-cache

build:branches:
  extends: .build:react
  stage: build
  needs:
  - compile
  only:
  - branches
  except:
  - production
  - tags
  script:
  - docker build -t $_img_repo/$_img_name:$_img_tag . --no-cache

push:
  extends: .push
  stage: registry
  only:
  - branches

push:tagged:
  extends: .push:tagged
  stage: registry
  only:
  - tags

deploy:review:
  extends: .deploy:review
  stage: deploy:review
  when: manual
  except:
    refs:
    - production

deploy:uat:
  extends: .deploy:uat
  stage: deploy:uat
  when: manual
  only:
    refs:
    - production

deploy:prod:
  extends: .deploy:prod
  stage: deploy:prod
  when: manual

abandon:
  extends: .abandon
  stage: deploy:review
